=== payne911/gdx-setup-generator/src/main/resources/json/libgdx-library-schema.json
{
  "$comment": "See 'JSON Schema Mappings' in IntelliJ to apply schema as a validator.",
  "$comment": "Use  { http://www.jsonschema2pojo.org/ }  to generate POJOs from this schema.",
  "$schema": "http://json-schema.org/draft-04/schema#",

  "type": "object",
  "required": [
    "formatVersion",
    "name",
    "authors",
    "description",
    "projectUrl",
    "states"
  ],
  "additionalProperties": false,
  "properties": {
    "formatVersion": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "description": {
      "type": "string"
    },
    "projectUrl": {
      "type": "string"
    },
    "states": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#state"
      }
    }
  },
  "definitions": {
    "state": {
      "$id": "#state",
      "type": "object",
      "properties": {
        "libraryVersion": {
          "type": "string"
        },
        "coreDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "desktopDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "gwtDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "androidDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "iOSDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "gwtInherits": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "androidPermissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "androidNativeDependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "incompatiblePlatforms": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "libraryVersion"
      ]
    }
  }
}

=== payne911/gdx-setup-generator/src/test/resources/json/library-examples/gdx-ai.json
{
  "formatVersion": 1,
  "name": "gdx-ai",
  "authors": [
    "libGDX-official-extension",
    "Tom-Ski"
  ],
  "description": "Artificial Intelligence framework for games based on libGDX or not. Features: Steering Behaviors, Formation Motion, Pathfinding, Behavior Trees and Finite State Machines.",
  "projectUrl": "https://github.com/libgdx/gdx-ai",
  "states": {
    "1.9.11": {
      "libraryVersion": "1.8.2",
      "coreDependencies": [
        "com.badlogicgames.gdx:gdx-ai"
      ],
      "gwtDependencies": [
        "com.badlogicgames.gdx:gdx-ai:sources"
      ],
      "gwtInherits": [
        "com.badlogic.gdx.ai"
      ]
    }
  }
}

=== payne911/gdx-setup-generator/src/test/resources/json/libgdx-library-example.json
{
  "formatVersion": 1,
  "name": "libgdx-screenmanager",
  "authors": [
    "damios"
  ],
  "description": "A screen manager for libgdx supporting transitions.",
  "projectUrl": "https://github.com/crykn/libgdx-screenmanager",
  "states": {
    "1.9.11": {
      "libraryVersion": "0.6.2",
      "coreDependencies": [
        "com.github.crykn:libgdx-screenmanager"
      ],
      "androidDependencies": [
        "org.xyz.android:whatever"
      ],
      "gwtDependencies": [
        "com.github.crykn:libgdx-screenmanager",
        "com.github.crykn:libgdx-screenmanager:sources",
        "com.github.crykn:libgdx-screenmanager-gwt",
        "com.github.crykn:libgdx-screenmanager-gwt:sources"
      ],
      "gwtInherits": [
        "libgdx_screenmanager",
        "libgdx_screenmanager_gwt"
      ],
      "androidPermissions": [
        "I_DONT_KNOW"
      ],
      "androidNativeDependencies": [
        "com.badlogicgames.gdx:gdx-box2d-platform:natives-armeabi",
        "com.badlogicgames.gdx:gdx-box2d-platform:natives-armeabi-v7a"
      ]
    },
    "1.9.10": {
      "libraryVersion": "0.5.1",
      "coreDependencies": [
        "com.github.crykn:libgdx-screenmanager"
      ],
      "gwtDependencies": [
        "com.github.crykn:libgdx-screenmanager",
        "com.github.crykn:libgdx-screenmanager:sources",
        "com.github.crykn:libgdx-screenmanager-gwt",
        "com.github.crykn:libgdx-screenmanager-gwt:sources"
      ],
      "gwtInherits": [
        "libgdx_screenmanager",
        "libgdx_screenmanager_gwt"
      ],
      "incompatiblePlatforms": [
        "android"
      ]
    }
  }
}
